from Book import *

books = [
    Book("To Kill a Mockingbird", "Harper Lee", 1960),
    Book("1984", "George Orwell", 1949),
    Book("Moby-Dick", "Herman Melville", 1851),
    Book("Pride and Prejudice", "Jane Austen", 1813),
    Book("The Great Gatsby", "F. Scott Fitzgerald", 1925),
    Book("War and Peace", "Leo Tolstoy", 1869),
    Book("Crime and Punishment", "Fyodor Dostoevsky", 1866),
    Book("The Catcher in the Rye", "J.D. Salinger", 1951),
    Book("The Odyssey", "Homer", -800),
    Book("The Iliad", "Homer", -750),
    Book("Brave New World", "Aldous Huxley", 1932),
    Book("The Grapes of Wrath", "John Steinbeck", 1939),
    Book("Jane Eyre", "Charlotte Brontë", 1847),
    Book("Wuthering Heights", "Emily Brontë", 1847),
    Book("Ulysses", "James Joyce", 1922),
    Book("The Hobbit", "J.R.R. Tolkien", 1937),
    Book("The Lord of the Rings", "J.R.R. Tolkien", 1954),
    Book("Fahrenheit 451", "Ray Bradbury", 1953),
    Book("Anna Karenina", "Leo Tolstoy", 1877),
    Book("The Picture of Dorian Gray", "Oscar Wilde", 1890),
    Book("Dracula", "Bram Stoker", 1897),
    Book("Frankenstein", "Mary Shelley", 1818),
    Book("One Hundred Years of Solitude", "Gabriel García Márquez", 1967),
    Book("Don Quixote", "Miguel de Cervantes", 1605),
    Book("Les Misérables", "Victor Hugo", 1862),
    Book("The Brothers Karamazov", "Fyodor Dostoevsky", 1880),
    Book("Madame Bovary", "Gustave Flaubert", 1856),
    Book("Great Expectations", "Charles Dickens", 1861),
    Book("David Copperfield", "Charles Dickens", 1850),
    Book("The Divine Comedy", "Dante Alighieri", 1320),
    Book("The Canterbury Tales", "Geoffrey Chaucer", 1400),
    Book("The Stranger", "Albert Camus", 1942),
    Book("The Trial", "Franz Kafka", 1925),
    Book("Lolita", "Vladimir Nabokov", 1955),
    Book("The Sound and the Fury", "William Faulkner", 1929),
    Book("Heart of Darkness", "Joseph Conrad", 1899),
    Book("The Old Man and the Sea", "Ernest Hemingway", 1952),
    Book("A Farewell to Arms", "Ernest Hemingway", 1929),
    Book("For Whom the Bell Tolls", "Ernest Hemingway", 1940),
    Book("Catch-22", "Joseph Heller", 1961),
    Book("Slaughterhouse-Five", "Kurt Vonnegut", 1969),
    Book("The Sun Also Rises", "Ernest Hemingway", 1926),
    Book("The Bell Jar", "Sylvia Plath", 1963),
    Book("Of Mice and Men", "John Steinbeck", 1937),
    Book("East of Eden", "John Steinbeck", 1952),
    Book("The Count of Monte Cristo", "Alexandre Dumas", 1844),
    Book("The Three Musketeers", "Alexandre Dumas", 1844),
    Book("The Metamorphosis", "Franz Kafka", 1915),
    Book("Gulliver's Travels", "Jonathan Swift", 1726),
    Book("The Tale of Two Cities", "Charles Dickens", 1859),
    Book("The Little Prince", "Antoine de Saint-Exupéry", 1943),
    Book("The Alchemist", "Paulo Coelho", 1988),
    Book("The Kite Runner", "Khaled Hosseini", 2003),
    Book("Life of Pi", "Yann Martel", 2001),
    Book("The Road", "Cormac McCarthy", 2006),
    Book("A Game of Thrones", "George R.R. Martin", 1996),
    Book("Harry Potter and the Sorcerer's Stone", "J.K. Rowling", 1997),
    Book("Harry Potter and the Chamber of Secrets", "J.K. Rowling", 1998),
    Book("The Hunger Games", "Suzanne Collins", 2008),
    Book("The Giver", "Lois Lowry", 1993),
    Book("Dune", "Frank Herbert", 1965),
    Book("The Handmaid's Tale", "Margaret Atwood", 1985),
    Book("The Shining", "Stephen King", 1977),
    Book("It", "Stephen King", 1986),
    Book("Misery", "Stephen King", 1987),
    Book("The Stand", "Stephen King", 1978),
    Book("Carrie", "Stephen King", 1974),
    Book("Ender's Game", "Orson Scott Card", 1985),
    Book("Neuromancer", "William Gibson", 1984),
    Book("The Left Hand of Darkness", "Ursula K. Le Guin", 1969),
    Book("The Dispossessed", "Ursula K. Le Guin", 1974),
    Book("A Clockwork Orange", "Anthony Burgess", 1962),
    Book("The Godfather", "Mario Puzo", 1969),
    Book("The War of the Worlds", "H.G. Wells", 1898),
    Book("Brave New World", "Aldous Huxley", 1932),
    Book("Atlas Shrugged", "Ayn Rand", 1957),
    Book("Gone with the Wind", "Margaret Mitchell", 1936),
    Book("The Hitchhiker's Guide to the Galaxy", "Douglas Adams", 1979),
    Book("The Call of the Wild", "Jack London", 1903),
    Book("White Fang", "Jack London", 1906),
    Book("Treasure Island", "Robert Louis Stevenson", 1883),
    Book("The Time Machine", "H.G. Wells", 1895),
    Book("Robinson Crusoe", "Daniel Defoe", 1719),
    Book("The Invisible Man", "H.G. Wells", 1897),
    Book("The Color Purple", "Alice Walker", 1982),
    Book("Beloved", "Toni Morrison", 1987),
    Book("The Poisonwood Bible", "Barbara Kingsolver", 1998),
    Book("Middlemarch", "George Eliot", 1871),
    Book("Mansfield Park", "Jane Austen", 1814),
    Book("Persuasion", "Jane Austen", 1817),
    Book("Northanger Abbey", "Jane Austen", 1817),
    Book("Sense and Sensibility", "Jane Austen", 1811),
    Book("Emma", "Jane Austen", 1815),
    Book("The Scarlet Letter", "Nathaniel Hawthorne", 1850),
    Book("The Adventures of Tom Sawyer", "Mark Twain", 1876),
    Book("The Adventures of Huckleberry Finn", "Mark Twain", 1884)
]